# config.toml

[theme]
# Cor primária para botões e elementos interativos
primaryColor="#6c63ff"

# Cor de fundo principal da aplicação
backgroundColor="#f0f2f6"

# Cor de fundo para elementos secundários (como a sidebar e containers)
# Esta é a cor que usaremos na sua coluna da direita!
secondaryBackgroundColor="#e8eaed"

# Cor do texto principal
textColor="#262730"

# Fonte
font="sans serif"